### ISSUE TITLE
SMP Crash

### ISSUE THREAD

**Issue by Chocohead** [EwyBoy/ITank#3]
Because `CommonProxy` is abstract, trying to use ITank on SMP will cause a crash because it can't create an instance: http://pastebin.com/cMBMLCTe.

**Comment by Vitamin-Carrot** [comment]
Yeah received a similar error server side

`[11:10:26] [Server thread/ERROR] [FML]: An error occurred trying to load a proxy into {serverSide=com.ewyboy.itank.proxy.CommonProxy, clientSide=com.ewyboy.itank.proxy.ClientProxy, modId=itank}.com.ewyboy.itank.ITank
java.lang.InstantiationException
	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48) ~[?:1.8.0_111]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_111]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_111]
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:71) [ProxyInjector.class:?]
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:577) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:549) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) [ld.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[11:10:27] [Server thread/ERROR] [snad]: The mod snad is expecting signature @FINGERPRINT@ for source Snad-1.10.2-1.6.09.20a.jar, however there is no signature matching that description
[11:10:27] [Server thread/ERROR] [Snad]: No fingerprint found!
[11:10:27] [Server thread/ERROR] [FML]: Fatal errors were detected during the transition from CONSTRUCTING to PREINITIALIZATION. Loading cannot continue
[11:10:27] [Server thread/ERROR] [FML]: 
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185-universal.jar) 
	UC	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185-universal.jar) 
	UC	appliedenergistics2-core{rv4-alpha-11} [Applied Energistics 2 Core] (minecraft.jar) 
	UC	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.0.jar) 
	UC	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.1.185-universal.jar) 
	UC	agriculturalexpansion{r-1.2.0} [Agricultural Expansion] (AgriculturalExpansion[1.9.4][1.10.2]-r1.2.2.jar) 
	UC	appliedenergistics2{rv4-alpha-11} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-11.jar) 
	UC	Aroma1997CoreHelper{1.1.1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.0.jar) 
	UC	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.9.4-1.2.0.2.jar) 
	UC	AutoSapling{1.3.3} [AutoSapling] (Autosapling-1.3.3-MC1.10.jar) 
	UC	Baubles{1.3.8} [Baubles] (Baubles-1.10.2-1.3.8.jar) 
	UC	bdlib{1.12.2.17} [BD Lib] (bdlib-1.12.2.17-mc1.10.2.jar) 
	UC	BiomesOPlenty{5.0.0.2109} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2109-universal.jar) 
	UC	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.10.2-1.5.1.jar) 
	UC	Botania{r1.9-339} [Botania] (Botania r1.9-339.jar) 
	UC	CodeChickenLib{2.5.1.185} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.1.185-universal.jar) 
	UC	brandonscore{2.1.3} [Brandon's Core] (BrandonsCore-1.10.2-2.1.3.82-universal.jar) 
	UC	cebm{1.0 by Dot_Silver} [Craftable Experience Bottle Mod - MCV 1.10.2] (cebm-mcv1.10.2.jar) 
	UC	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UC	CodeChickenCore{2.4.0.100} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.0.100-universal.jar) 
	UC	ChickenChunks{2.2.0.52} [ChickenChunks] (ChickenChunks-1.10.2-2.2.0.52-universal.jar) 
	UC	chickens{1.9.4-3.0} [Chickens] (chickens-1.9.4-3.0.jar) 
	UC	JEI{3.14.2.401} [Just Enough Items] (jei_1.10.2-3.14.2.401.jar) 
	UC	chiselsandbits{12.10} [Chisels & Bits] (chiselsandbits-12.10.jar) 
	UC	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(20nov16).jar) 
	UC	draconicevolution{2.0.6} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.6.157-universal.jar) 
	UC	enchiridion{3.1.15} [Enchiridion] (Enchiridion-1.10.2-3.1.15.jar) 
	UC	endercompass{1.2.3.2} [Ender Compass] (EnderCompass-1.9.x-1.2.3.2.jar) 
	UC	endercore{1.10.2-0.4.1.62-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.62-beta.jar) 
	UC	endercrop{1.9-1.2-1836} [Ender Crop] (endercrop-1.9.4-1.3.1.jar) 
	UC	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UC	EnderIO{1.10.2-3.1.156} [Ender IO] (EnderIO-1.10.2-3.1.156.jar) 
	UC	enderrift{1.5.0} [Ender-Rift] (EnderRift-1.10.2-1.5.0.jar) 
	UC	EnderStorage{2.2.0.96} [EnderStorage] (EnderStorage-1.10.2-2.2.0.96-universal.jar) 
	UC	valkyrielib{1.10.2-0.10.5d} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.5d.jar) 
	UC	environmentaltech{1.10.2-0.10.5e} [Environmental Tech] (environmentaltech-1.10.2-0.10.5e.jar) 
	UC	forestry{5.2.16.348} [Forestry] (forestry_1.10.2-5.2.16.348.jar) 
	UC	mantle{1.10.2-1.1.3.199} [Mantle] (Mantle-1.10.2-1.1.3.jar) 
	UC	tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct-1.10.2-2.6.1.jar) 
	UC	exnihiloomnia{1.2.1} [Ex Nihilo Omnia] (exnihiloomnia-1.2.1.jar) 
	UC	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.3d.jar) 
	UC	fairylights{2.0.1} [Fairy Lights] (fairylights-2.0.1-1.10.2.jar) 
	UC	ffs{1.10.2-2.0.3-b11} [Fancy Fluid Storage] (Fancy Fluid Storage-1.10.2-2.0.3-b11.jar) 
	UC	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UC	SonarCore{3.1.6} [SonarCore] (SonarCore-1.9.4-3.1.6.jar) 
	UC	FluxNetworks{1.0.7} [Flux Networks] (FluxNetworks-1.9.4-1.0.7.jar) 
	UC	gendustry{1.6.5.27} [GenDustry] (gendustry-1.6.5.27-mc1.10.2.jar) 
	UC	exp{1.1} [Exp Seedling Mod] (GiacomosExperienceSeedling1.9.4-1.1.jar) 
	UC	fishing{1.4.4} [Fishing Net Mod] (GiacomosFishingNet1.10.2-1.4.4.jar) 
	UC	immersiveengineering{0.10-54} [Immersive Engineering] (ImmersiveEngineering-0.10-54.jar) 
	UC	InfernalMobs{1.7.1} [Infernal Mobs] (InfernalMobs-1.10.2.jar) 
	UC	infinitylib{1.10.2-0.3.0} [InfinityLib] (infinitylib-0.3.0.jar) 
	UC	InventoryPets{1.4.9} [Inventory Pets] (inventorypets-1.10-1.4.9.jar) 
	UC	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UE	itank{1.0.0-1.10.2} [ITank] (ITank-1.0.0-1.10.2.jar) 
	UC	jlgm_caod{1.10.2-0.1.0-hotfixOfTheHotfix} [Cock-an-ore-doo] (jlgm_caod-1.10.2-0.1.0-hotfixOfTheHotfix.jar) 
	UC	journeymap{1.10.2-5.3.0b1} [JourneyMap] (journeymap-1.10.2-5.3.0b1-unlimited.jar) 
	UC	lootbags{2.1.3} [Loot Bags] (LootBags-1.10.2-2.1.3.jar) 
	UC	minecolonies{1.10.2-0.6.2038} [MineColonies] (minecolonies-universal-1.10.2-0.6.2038.jar) 
	UC	morechickens{1.0.0} [More Chickens] (MoreChickens-1.10.2-1.0.4.jar) 
	UC	shetiphiancore{3.3.6} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.6.jar) 
	UC	multistorage{1.2.13} [Multi-Storage] (multistorage-1.10.0-1.2.13.jar) 
	UC	natura{1.10.2-4.1.0.17} [Natura] (natura-1.10.2-4.1.0.17.jar) 
	UC	harvestcraft{1.9.4-1.10.2f} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2f.jar) 
	UC	rftools{5.76} [RFTools] (rftools-1.1x-5.76.jar) 
	UC	rftoolsdim{4.52} [RFTools Dimensions] (rftoolsdim-1.1x-4.52.jar) 
	UC	PersistentBits{1.0.5} [Persistent Bits] (PersistentBits-1.10.2-1.0.5.jar) 
	UC	railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
	UC	randomthings{3.7.7} [Random Things] (RandomThings-MC1.10.2-3.7.7.jar) 
	UC	reborncore{2.12.1.96} [RebornCore] (RebornCore-1.10.2-2.12.1.96-universal.jar) 
	UC	reborncore-mcmultipart{2.12.1.96} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.12.1.96-universal.jar) 
	UC	rftoolscontrol{1.6.3} [RFTools Control] (rftoolsctrl-1.1x-1.6.3.jar) 
	UC	roots{0.208} [Roots] (roots-0.208.jar) 
	UC	showcasemod{0.4} [Showcase Mod] (showcasemod-0.4.jar) 
	UC	simplyjetpacks{2.0.2.9} [Simply Jetpacks 2] (SimplyJetpacks2-1.10.2-2.0.2.9.jar) 
	UC	snad{1.10.2-1.6.09.20a} [Snad] (Snad-1.10.2-1.6.09.20a.jar) 
	UC	SolarFluxReborn{1.4r} [Solar Flux Reborn] (SolarFluxReborn_1.10.2-1.4r.jar) 
	UC	StorageDrawers{1.10.2-3.5.16} [Storage Drawers] (StorageDrawers-1.10.2-3.5.16.jar) 
	UC	superores{1.7} [Super Ores] (SuperOres-1.7.jar) 
	UC	taiga{1.2.4} [Tinkers Alloying Addon] (taiga-1.10.2-1.2.4.jar) 
	UC	techreborn{1.4.17.141} [TechReborn] (TechReborn-1.10.2-1.4.17.141-universal.jar) 
	UC	thutessentials{1.5.25} [Thut Essentials] (thutessentials-1.5.25.jar) 
	UC	thutperms{0.1.1} [Thut Permissions] (thutpermissions-0.4.0.jar) 
	UC	TinkersAddons{1.0.3} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.3.jar) 
	UC	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UC	tp{1.0.0} [Tiny Progressions] (tinyprogressions-1.10.2-1.0.9-release.jar) 
	UC	Torcherino{4.2s} [Torcherino] (Torcherino-4.2s.jar) 
	UC	Translocator{2.1.3.49} [Translocator] (Translocators-1.10.2-2.1.3.49-universal.jar) 
	UC	waterstrainer{1.3.0} [Water Strainer] (WaterStrainer-1.9.4-1.3.0.jar) 
[11:10:27] [Server thread/ERROR] [FML]: The following problems were captured during this phase
[11:10:27] [Server thread/ERROR] [FML]: Caught exception from ITank (itank)
net.minecraftforge.fml.common.LoaderException: java.lang.InstantiationException

	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:88) ~[forge-1.10.2-12.18.3.2185-universal.jar:?]
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:577) ~[forge-1.10.2-12.18.3.2185-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) ~[forge-1.10.2-12.18.3.2185-universal.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) ~[forge-1.10.2-12.18.3.2185-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:549) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) [ld.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.InstantiationException
	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48) ~[?:1.8.0_111]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_111]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_111]
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:71) ~[forge-1.10.2-12.18.3.2185-universal.jar:?]
	... 27 more
[11:10:27] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ITank (itank)

Caused by: net.minecraftforge.fml.common.LoaderException: java.lang.InstantiationException

	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:88) ~[forge-1.10.2-12.18.3.2185-universal.jar:?]
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:577) ~[forge-1.10.2-12.18.3.2185-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:549) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[ld.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.InstantiationException
	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48) ~[?:1.8.0_111]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_111]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_111]
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:71) ~[forge-1.10.2-12.18.3.2185-universal.jar:?]
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:577) ~[forge-1.10.2-12.18.3.2185-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.10.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:549) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[ld.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_111]
[11:10:27] [Server thread/ERROR]: This crash report has been saved to: /home/vitamin-carrot/mcfserver1/./crash-reports/crash-2017-01-12_11.10.27-server.txt
[11:10:27] [Server thread/INFO]: Stopping server
[11:10:27] [Server thread/INFO]: Saving worlds
[11:10:27] [Server thread/WARN] [FML]: Can't revert to frozen GameData state without freezing first.
[11:10:27] [Server thread/INFO] [mcjty.lib.varia.Logging]: RFTools: server is stopping. Shutting down gracefully
[11:10:27] [Server thread/INFO] [mcjty.lib.varia.Logging]: RFTools: server is stopping. Shutting down gracefully
[11:10:28] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[11:10:28] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.
`

**Comment by EwyBoy** [comment]
A fix is on the way

**Comment by Vitamin-Carrot** [comment]
Oh I cant wait - these tanks look mint - cheers ears

**Comment by EwyBoy** [comment]
![image](https://cloud.githubusercontent.com/assets/5883716/21869637/d90fe19e-d858-11e6-8f31-23d0610352cb.png)

Got it working now, let me build and push it to CurseForge.

**Comment by EwyBoy** [comment]
https://minecraft.curseforge.com/projects/itank/files/2367130

**Comment by Vitamin-Carrot** [comment]
Confirmed resolved -

Awesome work dude - any plans on implementing a right click interaction when the tank is full of XP?

On 12/01/2017 12:22 PM, EwyBoy wrote:

https://minecraft.curseforge.com/projects/itank/files/2367130

**Comment by EwyBoy** [comment]
yes I am planning to do it
